<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Webjump\BraspagPagador\Block\Payment\Info\Boleto $block
 * @see \Webjump\BraspagPagador\Block\Payment\Info\Boleto
 */
$specificInfo = $block->getSpecificInformation();
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>

<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value):?>
            <tr>
                <?php if($label === (string) __('Print Boleto')): ?>
                    <td colspan="2">
                        <a class="action-default" target="_blank" href="<?php echo $value?>"><?php echo __('Print Boleto') ?></a>
                    </td>
                    <?php continue;?>
                <?php endif;?>
                <th><?php echo $block->escapeHtml($label)?>:</th>
                <td>
                    <?php /* @noEscape */ echo nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))));?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?php echo $block->getChildHtml()?>
