<?php
/**
 * @var \Braspag\BraspagPagador\Block\Payment\Info\CreditCard $block
 * @see \Braspag\BraspagPagador\Block\Payment\Info\CreditCard
 */
$specificInfo = $block->getSpecificInformation();
?>

<?php if ($specificInfo) : ?>
<div class="admin__page-section-item-content">
    <p><?php echo $block->getCardCcOwner();?></p>
    <p><?php echo $block->getCardInfo(); ?></p>                
    <p><?php echo $block->getInstallmentsInfo(); ?></p>
    <?php if($block->hasTwoCard()):?>
       <hr></hr>
       <p><?php echo $block->getTwoCardCcOwner();?></p>
       <p><?php echo $block->getCardInfoTwoCard(); ?></p>
       <p><?php echo $block->getInstallmentsInfoTwoCard(); ?></p>
    <?php endif;?>
</div>
<?php endif;?>

<?php echo $block->getChildHtml()?>