<?php
/**
 * @author      Webjump Core Team <dev@webjump.com>
 * @copyright   2016 Webjump (http://www.webjump.com.br)
 * @license     http://www.webjump.com.br  Copyright
 *
 * @link        http://www.webjump.com.br
 *
 * @var \Webjump\BraspagPagador\Block\Checkout\Onepage\Transaction\Billet\Link $this
 */
?>
<?php if ($this->getBilletUrl()): ?>
    <hr />
    <a class="action tocart primary" href="<?php echo $this->getBilletUrl() ?>" target="_blank"><?php echo __('Print Billet') ?></a>
<?php endif ?>
