<?php
/**
 * @var \Braspag\BraspagPagador\Block\Payment\Info\CreditCard $block
 * @see \Braspag\BraspagPagador\Block\Payment\Info\CreditCard
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><?php /* @noEscape */ echo $title; ?></dt>
    <?php if ($specificInfo) :?>
    <dd class="content">
        <table class="data table">
            <caption class="table-caption"><?php /* @noEscape */ echo $title; ?></caption>
            <div class="admin__page-section-item-content">
                <p><?php echo $block->escapeHtml($specificInfo['brand']) . ' - ##########' . $block->escapeHtml($specificInfo['last_4_digits']);?>
                </p>
                <p><?php echo $block->getInstallmentsInfo(); ?></p>
                <?php if($block->hasTwoCard()):?>
                            <hr></hr>
                        <p><?php echo $block->escapeHtml($specificInfo['cc_owner_two_card']);?></p>
                        <p><?php echo $block->escapeHtml($specificInfo['brand_two_card']) . ' - ##########' . $block->escapeHtml($specificInfo['last_4_digits_two_card']);?></p>
                        <p><?php echo $block->getInstallmentsInfoTwoCard(); ?></p>
                <?php endif;?>
            </div>
        </table>
    </dd>
    <?php endif;?>
</dl>

<?php echo $block->getChildHtml()?>